name: CI

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
      - run: |
          echo "APP_ENV=prod" >> .env
          echo "APP_SECRET=your_secret_key" >> .env
          echo "DATABASE_URL=mysql://db_user:db_password@127.0.0.1:3306/db_name" >> .env
      - run: composer install
      - run: ./vendor/bin/php-cs-fixer fix --dry-run --diff
